### ISSUE TITLE
Ignore the __pycache__ folder

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/hlt-umd#5]
Hi @emilyj816 

Typically the `__pycache__` folder is not added to git repo, because these are compiled Python bytecode that are OS- and Python-interpreter-version-specific.

If you don't mind, I can remove that folder from this project and add a `.gitignore` rule so that they won't get added accidentally in the future. What do you think?

**Comment by emilyj816** [comment]
Hi Yipeng,

That’s a great idea, thanks for the suggestion!

Emily
